sudo: required
services: 
    - docker

before_install:
    - docker build -t johnlight777/docker-react -f Dockerfile.dev .

script:
    - docker run johnlight777/docker-react npm run test -- --coverage
